compute_environment: LOCAL_MACHINE
distributed_type: "NO"
mixed_precision: fp16
num_processes: 1
num_machines: 1
machine_rank: 0
gpu_ids: "0"
same_network: true
main_training_function: main
use_cpu: false
dynamo_backend: "NO"
downcast_bf16: false
